In [1]:
def func (*args, b=2):
    results = (all(args), b)
    return sum(results) == b

func(7, 6, 7, 0, b=6)

True

In [2]:
import numpy as np

### np.where(condition, [x, y, ]/) 
Return elements chosen from x or y depending on condition.<br>
When only condition is provided, this function is a shorthand for **np.asarray(condition).nonzero()**. Using nonzero directly should be preferred, as it behaves correctly for subclasses.

当condition是一个条件表达式时，np.asarray(condition).nonzero() 的作用是返回满足条件的元素的索引，即在condition中为True的元素所在的位置。这里需要注意的是，condition是一个布尔数组，因此True表示该位置的元素满足条件，False表示该位置的元素不满足条件。
例如：

In [14]:
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 2
result = np.asarray(condition).nonzero()
print(result)

(array([2, 3, 4], dtype=int64),)


(array([2, 3, 4], dtype=int64),) 指的是满足condition的index

In [15]:
resulting_loss = [2.3, 5, 9, 1.2]
np.where(resulting_loss == np.min(resulting_loss))

(array([3], dtype=int64),)

(array([3], dtype=int64),) 指满足condition的元素的index是3，也就是原list中的1.2

In [5]:
np.where(resulting_loss == np.min(resulting_loss))[0][0]

3

这里需要用[0][0]来取出满足条件的第一个元素是因为，np.where返回的是一个tuple，这个tuple只含有一个元素，是一个1D数组。<br>
因此第一个[0]用来访问这个数组，第二个[0]访问该数组中的第一个元素

### tuple, list, array

list, tuple是Python内置的数据类型，array是Numpy库的

list是一种有序的可变序列(Mutable)，可以随时添加和删除其中的元素，可以存储任意类型的对象，括整数、浮点数、字符串、布尔值等等<br>
tuple是一种有序的不可变序列，通常包含不同类型的元素。元组中的元素可以通过索引访问，但是不能更改。元组一旦创建就不能修改，这使得它们在存储固定数据时非常有用<br>
array是一种数组类型，它可以包含相同类型的多个元素。数组中的元素可以通过索引访问。数组的长度可以在创建时指定，并且可以随时更改<br>

In [46]:
## define a function, which gets the slice from the middle node of a head till the end

def middleNode(head):

    middleNode_idx = len(head) // 2
    rest_idx = list(range(middleNode_idx, len(head)))
    rest = [head[i] for i in rest_idx]
    return rest

x = [1, 2, 3, 4, 5, 6]
middleNode(x)

[4, 5, 6]